#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
# SPDX-License-Identifier: MIT
"""Generates src/secp256k1_tables.rs, the fixed-base tables src/ecrecover.rs multiplies G with.

    gen_tables.py            rewrite src/secp256k1_tables.rs
    gen_tables.py --check    fail if the checked-in file differs from a fresh one
"""

import sys
from pathlib import Path

P = 2**256 - 2**32 - 977
G = (0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
     0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8)
# A cube root of unity mod p; (x, y) -> (BETA * x, y) multiplies a point by LAMBDA (a cube root of unity mod n).
BETA = 0x7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE

WINDOW_G = 8
ENTRIES = 1 << (WINDOW_G - 2)


def add(a, b):
    if a == b:
        m = 3 * a[0] * a[0] * pow(2 * a[1], -1, P)
    else:
        m = (b[1] - a[1]) * pow(b[0] - a[0], -1, P)
    x = (m * m - a[0] - b[0]) % P
    return x, (m * (a[0] - x) - a[1]) % P


def odd_multiples(base):
    twice = add(base, base)
    table = [base]
    for _ in range(ENTRIES - 1):
        table.append(add(table[-1], twice))
    return table


def limbs(v):
    return ", ".join(f"0x{(v >> (64 * i)) & (2**64 - 1):016x}" for i in range(4))


def emit(name, comment, points):
    lines = [f"/// {comment}",
             f"pub(crate) static {name}: [Point; ENTRIES_G] = unsafe {{",
             f"    core::mem::transmute::<[[u64; 8]; ENTRIES_G], [Point; ENTRIES_G]>([",
             ]
    for x, y in points:
        lines.append(f"        [{limbs(x)},")
        lines.append(f"         {limbs(y)}],")
    lines.append("    ])")
    lines.append("};")
    return "\n".join(lines)


def render():
    g = odd_multiples(G)
    lambda_g = [(BETA * x % P, y) for x, y in g]
    return "\n".join([
        "// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited",
        "// SPDX-License-Identifier: MIT",
        "",
        "//! Generated by gen_tables.py - do not edit.",
        "//!",
        "//! Each point is its x then its y coordinate, as little-endian 64-bit limbs:",
        "//! the in-memory layout of `Secp256k1Point` on a little-endian target.",
        "",
        "use openvm_k256::Secp256k1Point as Point;",
        "",
        f"pub(crate) const WINDOW_G: u32 = {WINDOW_G};",
        f"const ENTRIES_G: usize = {ENTRIES};",
        "",
        emit("G_TABLE", "(2i + 1) * G", g),
        "",
        emit("NEG_G_TABLE", "-(2i + 1) * G", [(x, P - y) for x, y in g]),
        "",
        emit("LAMBDA_G_TABLE", "(2i + 1) * lambda * G = (beta * x, y) of the G_TABLE entry", lambda_g),
        "",
        emit("NEG_LAMBDA_G_TABLE", "-(2i + 1) * lambda * G", [(x, P - y) for x, y in lambda_g]),
        "",
    ])


def main():
    path = Path(__file__).parent / "src" / "secp256k1_tables.rs"
    text = render()
    if sys.argv[1:] == ["--check"]:
        if path.read_text() != text:
            sys.exit(f"{path.name} is stale; rerun {Path(__file__).name}")
        print(f"{path.name} is up to date")
    else:
        path.write_text(text, newline="\n")


if __name__ == "__main__":
    main()
